### ISSUE TITLE
licenseについて

### ISSUE THREAD

**Issue by tanetakumi** [sasadd-LAB/SasaLauncher2#1]
[SasaLauncher2](https://github.com/sasadd-LAB/SasaLauncher2)は素晴らしいプロジェクトだと思います。
私もこれをForkして使用してみたいのですがライセンスはどのようになっていますか？
よろしくお願いします。

**Comment by ddPn08** [comment]
反応出来ずにいて申し訳ないです。
自鯖で使うだけの予定だったのでライセンスについては全く考えていなかったのですが、MITライセンスとさせていただきます。
ただこのプロジェクトはもう開発を進める予定はないのでその点ご了承ください。
